language: node_js
branches:
  only:
    - master
node_js:
  - '8'
script:
  - npm run lint
  - npm run build
  - npm test
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
